package com.example.demo.controller.dto;

import lombok.Data;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

/**
* Generated by Springboot-3layer-Generator at Jan 6, 2021, 8:30:41 PM
*/
@Data
public class BookDTO {

    private long serialVersionUID;
    private java.lang.Integer bookId;
    private java.lang.String author;
    private java.lang.String isbn;
    private java.lang.String title;
    private java.lang.Integer year;
    private java.util.List orders;

}
