package com.example.demo.controller.dto;

import lombok.Data;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

/**
* Generated by Springboot-3layer-Generator at 31 ott 2020, 17:25:45
*/
@Data
public class CartsDTO {

    private java.lang.Integer userId;
    private java.lang.Integer bookId;
    private java.lang.Integer quantity;

}
