package com.example.demo.controller.dto;

import lombok.Data;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

/**
* Generated by Springboot-3layer-Generator at 1 nov 2020, 11:10:29
*/
@Data
public class CartsDTO {

    private java.lang.Integer userId;
    private java.lang.Integer bookId;
    private java.lang.Integer quantity;

}
