package com.example.demo.controller.dto;

import lombok.Data;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

/**
* Generated by Springboot-3layer-Generator at 31 ott 2020, 17:25:45
*/
@Data
public class PersonphoneDTO {

    private java.lang.Integer businessentityid;
    private java.lang.Integer phonenumber;
    private java.lang.Integer phonenumbertypeid;
    private java.sql.Timestamp modifieddate;

}
