package com.example.demo.controller.dto;

import lombok.Data;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

/**
* Generated by Springboot-3layer-Generator at Dec 25, 2020, 8:12:32 PM
*/
@Data
public class UsersDTO {

    private java.lang.Integer userId;
    private java.lang.String firstName;
    private java.lang.String lastName;

}
