package com.example.demo.controller.dto;

import lombok.Data;

/**
* Generated by Springboot-3layer-Generator at Feb 20, 2023, 3:17:23 PM
*/
@Data
public class UserDTO {

    private long serialVersionUID;
    private java.lang.Integer userId;
    private java.lang.String firstName;
    private java.lang.String lastName;
    private java.util.List orders;

}
