package com.example.demo.controller.dto;

import lombok.Data;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

/**
* Generated by Springboot-3layer-Generator at Jan 23, 2023, 12:19:32 PM
*/
@Data
public class UserDTO {

    private long serialVersionUID;
    private java.lang.Integer userId;
    private java.lang.String firstName;
    private java.lang.String lastName;
    private java.util.List orders;

}
