package com.autogen.example.repository;

import com.autogen.example.model.Carts;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
* Generated by Springboot-3layer-Generator at 27 ott 2020, 19:52:19
*/
@Repository
public interface CartsRepository extends JpaRepository<Carts, java.lang.Integer> {

}