package com.example.demo.controller;

import com.example.demo.model.Book;
import com.example.demo.serviceInterface.BookService;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Pageable;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import java.util.Optional;

/**
* Generated by Springboot-3layer-Generator at Feb 26, 2023, 4:08:34 PM
*/
@RestController
@RequestMapping("/book/")
public class BookController implements CrudController<Book,java.lang.Integer>{

    @Autowired
    private BookService service;

    @Override
    public ResponseEntity<Book> create(@RequestBody Book entity) {
        return ResponseEntity.ok(service.create(entity));
    }

    @Override
    public ResponseEntity<Book> update(@RequestBody Book entity) {
        return ResponseEntity.ok(service.update(entity));
    }

    @Override
    public ResponseEntity<Page<Book>> find(
            @RequestBody Book entity,
            @RequestParam("page") Integer page,
            @RequestParam("size") Integer size) {
        Pageable pageable = PageRequest.of(page,size);
        return ResponseEntity.ok(service.find(entity,pageable));
    }

    @Override
    public ResponseEntity<Book> getOne(@PathVariable("id") java.lang.Integer primaryKey) {
        return service.getOne(primaryKey).map(ResponseEntity::ok).orElseGet(() -> ResponseEntity.notFound().build());
    }

    @Override
    public void delete(java.lang.Integer primaryKey) {
        service.delete(primaryKey);
    }
}