package com.example.demo.controller;

import com.example.demo.model.User;
import com.example.demo.serviceInterface.UserService;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Pageable;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import java.util.Optional;

/**
* Generated by Springboot-3layer-Generator at Feb 21, 2023, 6:23:13 AM
*/
@RestController
@RequestMapping("/user/")
public class UserController implements CrudController<User,java.lang.Integer>{

    @Autowired
    private UserService service;

    @Override
    public ResponseEntity<User> create(@RequestBody User entity) {
        return ResponseEntity.ok(service.create(entity));
    }

    @Override
    public ResponseEntity<User> update(@RequestBody User entity) {
        return ResponseEntity.ok(service.update(entity));
    }

    @Override
    public ResponseEntity<Page<User>> read(
            @RequestParam("page") Integer page,
            @RequestParam("size") Integer size) {
        Pageable pageable = PageRequest.of(page,size);
        return ResponseEntity.ok(service.read(pageable));
    }

    @Override
    public ResponseEntity<User> readOne(@PathVariable("id") java.lang.Integer primaryKey) {
        return service.readOne(primaryKey).map(ResponseEntity::ok).orElseGet(() -> ResponseEntity.notFound().build());
    }

    @Override
    public void delete(java.lang.Integer primaryKey) {
        service.delete(primaryKey);
    }
}