projectPath: /home/tano/workspace_autogenerate/springboot-3layer-generator
outputDirectory : /src/main/java
options:
  dtoLayer : true

inputPackages:
  jpaEntities : com.autogen.example.model

outputPackages:
  repositories : com.autogen.example.repository
  services: com.autogen.example.service
  controllers: com.autogen.example.controller