package com.example.demo.service;

import com.example.demo.model.Book;

/**
* Generated by Springboot-3layer-Generator at Jan 6, 2021, 8:30:41 PM
*/
public interface BookService extends CrudService<Book,java.lang.Integer> {

}