package com.example.demo.service;

import com.example.demo.model.Book;

/**
* Generated by Springboot-3layer-Generator at Jan 23, 2023, 10:03:25 AM
*/
public interface BookService extends CrudService<Book,java.lang.Integer> {

}