package com.example.demo.service;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import java.util.Optional;

/**
* Generated by Springboot-3layer-Generator at Feb 20, 2023, 3:17:23 PM
*/
public interface CrudService<E, P> {

    E create(E entity);

    E update(E entity);

    Page<E> read(Pageable pageable);

    Optional<E> readOne(P primaryKey);

    void delete(P primaryKey);

}