package com.example.demo.service;

import com.example.demo.model.Order;

/**
* Generated by Springboot-3layer-Generator at Jan 6, 2021, 8:30:41 PM
*/
public interface OrderService extends CrudService<Order,java.lang.Integer> {

}