package com.example.demo.service;

import com.example.demo.model.User;

/**
* Generated by Springboot-3layer-Generator at Jan 6, 2021, 8:30:41 PM
*/
public interface UserService extends CrudService<User,java.lang.Integer> {

}