package ${config.outputPackages.controllers}.dto;

import lombok.Data;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

/**
* Generated by Springboot-3layer-Generator at ${dateGen?datetime}
*/
@Data
public class ${entityClass}DTO {

<#list entityFields as field>
    private ${field.type.name} ${field.name};
</#list>

}

