package ${config.outputPackages.dtos};

import lombok.Data;

/**
* Generated by Springboot-3layer-Generator at ${dateGen?datetime}
*/
@Data
public class ${entityClass}DTO {

<#list entityFields as field>
    private ${field.type.name} ${field.name};
</#list>

}

