package ${config.outputPackages.services}.mapper;

import ${entityPackage}.${entityClass};
import ${config.outputPackages.controllers}.dto.${entityClass}DTO;
import org.mapstruct.Mapper;

/**
* Generated by Springboot-3layer-Generator at ${dateGen?datetime}
*/
@Mapper(componentModel = "spring")
public interface ${entityClass}Mapper {

    ${entityClass} toEntity(${entityClass}DTO dto);

    ${entityClass}DTO toDto(${entityClass} entity);

}