package ${config.outputPackages.repositories};

import ${config.inputPackages.jpaEntities}.${entityClass};
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
* Generated by Springboot-3layer-Generator at ${dateGen?datetime}
*/
@Repository
public interface ${entityClass}Repository extends JpaRepository<${entityClass}, ${primaryKeyClass}> {

}
