package ${config.outputPackages.services};

import ${entityPackage}.${entityClass};

/**
* Generated by Springboot-3layer-Generator at ${dateGen?datetime}
*/
public interface ${entityClass}Service extends CrudService<${entityClass},${primaryKeyClass}> {

}
