projectPath: /home/tano/workspace_autogenerate/springboot-3layer-generator
outputDirectory : /src/main/java
options:
    dtoLayer : true

inputPackages:
    jpaEntities : com.gae.piaz.autogen.model

outputPackages:
    repositories : com.gae.piaz.autogen.repositorygen
    services: com.gae.piaz.autogen.servicegen
    controllers: com.gae.piaz.autogen.controllergen
  



