package com.example.demo.serviceInterface.impl;

import com.example.demo.model.Orders;
import com.example.demo.repository.OrdersRepository;
import com.example.demo.serviceInterface.OrdersService;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Example;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;

/**
* Generated by Springboot-3layer-Generator at Dec 25, 2020, 8:12:32 PM
*/
@Service
public class OrdersServiceBean implements OrdersService {

    @Autowired
    private OrdersRepository repository;

    @Override
    public Orders create(Orders entity) {
        return repository.save(entity);
    }

    @Override
    public Orders update(Orders entity) {
        return repository.save(entity);
    }

    @Override
    public Page<Orders> read(Orders entity, Pageable pageable) {
        Example<Orders> example = Example.of(entity);
        return repository.findAll(example,pageable);
    }

    @Override
    public Orders readOne(java.lang.Integer primaryKey) {
        return repository.getOne(primaryKey);
    }

    @Override
    public void delete(java.lang.Integer primaryKey) {
        repository.deleteById(primaryKey);
    }
}