package com.example.demo.service;

import com.example.demo.model.Book;

/**
* Generated by Springboot-3layer-Generator at Feb 20, 2023, 3:17:23 PM
*/
public interface BookService extends CrudService<Book,java.lang.Integer> {

}