package com.example.demo.service;

import com.example.demo.model.Order;

/**
* Generated by Springboot-3layer-Generator at Feb 26, 2023, 4:26:01 PM
*/
public interface OrderService extends CrudService<Order,java.lang.Integer> {

}