package com.example.demo.service;

import com.example.demo.model.User;

/**
* Generated by Springboot-3layer-Generator at Jan 23, 2023, 12:19:32 PM
*/
public interface UserService extends CrudService<User,java.lang.Integer> {

}