package com.example.demo.service;

import com.example.demo.model.User;

/**
* Generated by Springboot-3layer-Generator at Feb 20, 2023, 3:17:23 PM
*/
public interface UserService extends CrudService<User,java.lang.Integer> {

}