package com.example.demo.service;

import com.example.demo.model.User;

/**
* Generated by Springboot-3layer-Generator at Feb 26, 2023, 4:26:01 PM
*/
public interface UserService extends CrudService<User,java.lang.Integer> {

}