package com.example.demo.serviceInterface;

import com.example.demo.model.Book;

/**
* Generated by Springboot-3layer-Generator at Feb 26, 2023, 4:08:34 PM
*/
public interface BookService extends CrudService<Book,java.lang.Integer> {

}