package com.example.demo.serviceInterface;

import com.example.demo.model.Books;

/**
* Generated by Springboot-3layer-Generator at Dec 25, 2020, 8:12:32 PM
*/
public interface BooksService extends CrudService<Books,java.lang.Integer> {

}