package com.example.demo.serviceInterface;

import com.example.demo.model.Book;

/**
* Generated by Springboot-3layer-Generator at Feb 21, 2023, 6:23:13 AM
*/
public interface BookService extends CrudService<Book,java.lang.Integer> {

}