package com.example.demo.serviceInterface;

import com.example.demo.model.Order;

/**
* Generated by Springboot-3layer-Generator at Jan 23, 2023, 10:35:29 AM
*/
public interface OrderService extends CrudService<Order,java.lang.Integer> {

}