package com.example.demo.serviceInterface;

import com.example.demo.model.Order;

/**
* Generated by Springboot-3layer-Generator at Feb 26, 2023, 4:20:30 PM
*/
public interface OrderService extends CrudService<Order,java.lang.Integer> {

}