package com.example.demo.serviceInterface;

import com.example.demo.model.Users;

/**
* Generated by Springboot-3layer-Generator at Dec 25, 2020, 8:12:32 PM
*/
public interface UsersService extends CrudService<Users,java.lang.Integer> {

}