package com.example.demo.serviceInterface;

import com.example.demo.model.User;

/**
* Generated by Springboot-3layer-Generator at Jan 23, 2023, 10:35:30 AM
*/
public interface UserService extends CrudService<User,java.lang.Integer> {

}