package com.example.demo.serviceInterface;

import com.example.demo.model.User;

/**
* Generated by Springboot-3layer-Generator at Feb 26, 2023, 4:08:34 PM
*/
public interface UserService extends CrudService<User,java.lang.Integer> {

}