package com.example.demo.serviceInterface.mapper;

import com.example.demo.model.Carts;
import com.example.demo.controller.dto.CartsDTO;
import org.mapstruct.Mapper;

/**
* Generated by Springboot-3layer-Generator at Dec 25, 2020, 8:12:32 PM
*/
@Mapper(componentModel = "spring")
public interface CartsMapper {

    Carts toEntity(CartsDTO dto);

    CartsDTO toDto(Carts entity);

}