package com.example.demo.serviceInterface.mapper;

import com.example.demo.model.Orders;
import com.example.demo.controller.dto.OrdersDTO;
import org.mapstruct.Mapper;

/**
* Generated by Springboot-3layer-Generator at Dec 25, 2020, 8:12:32 PM
*/
@Mapper(componentModel = "spring")
public interface OrdersMapper {

    Orders toEntity(OrdersDTO dto);

    OrdersDTO toDto(Orders entity);

}