package com.example.demo.serviceInterface.mapper;

import com.example.demo.model.Order;
import com.example.demo.controller.dto.OrderDTO;
import org.mapstruct.Mapper;

/**
* Generated by Springboot-3layer-Generator at Jan 23, 2023, 10:35:30 AM
*/
@Mapper(componentModel = "spring")
public interface OrderMapper {

    Order toEntity(OrderDTO dto);

    OrderDTO toDto(Order entity);

}