package com.example.demo.serviceInterface.mapper;

import com.example.demo.model.Users;
import com.example.demo.controller.dto.UsersDTO;
import org.mapstruct.Mapper;

/**
* Generated by Springboot-3layer-Generator at Dec 25, 2020, 8:12:32 PM
*/
@Mapper(componentModel = "spring")
public interface UsersMapper {

    Users toEntity(UsersDTO dto);

    UsersDTO toDto(Users entity);

}