package com.example.demo.serviceInterface;

import com.example.demo.model.User;

/**
* Generated by Springboot-3layer-Generator at Feb 22, 2023, 1:38:03 PM
*/
public interface UserService extends CrudService<User,java.lang.Integer> {

}