package com.example.demo.serviceInterface;

import com.example.demo.model.User;

/**
* Generated by Springboot-3layer-Generator at Feb 21, 2023, 8:01:16 AM
*/
public interface UserService extends CrudService<User,java.lang.Integer> {

}