package com.autogen.example.service.mapper;

import com.autogen.example.model.Books;
import com.autogen.example.controller.dto.BooksDTO;
import org.mapstruct.Mapper;

/**
* Generated by Springboot-3layer-Generator at 27 ott 2020, 19:52:19
*/
@Mapper(componentModel = "spring")
public interface BooksMapper {

    Books toEntity(BooksDTO dto);

    BooksDTO toDto(Books entity);

}