package com.autogen.example.service.mapper;

import com.autogen.example.model.Orders;
import com.autogen.example.controller.dto.OrdersDTO;
import org.mapstruct.Mapper;

/**
* Generated by Springboot-3layer-Generator at 27 ott 2020, 19:52:19
*/
@Mapper(componentModel = "spring")
public interface OrdersMapper {

    Orders toEntity(OrdersDTO dto);

    OrdersDTO toDto(Orders entity);

}