package com.autogen.example.service.mapper;

import com.autogen.example.model.Personphone;
import com.autogen.example.controller.dto.PersonphoneDTO;
import org.mapstruct.Mapper;

/**
* Generated by Springboot-3layer-Generator at 27 ott 2020, 19:52:19
*/
@Mapper(componentModel = "spring")
public interface PersonphoneMapper {

    Personphone toEntity(PersonphoneDTO dto);

    PersonphoneDTO toDto(Personphone entity);

}