package com.autogen.example.service.mapper;

import com.autogen.example.model.Users;
import com.autogen.example.controller.dto.UsersDTO;
import org.mapstruct.Mapper;

/**
* Generated by Springboot-3layer-Generator at 27 ott 2020, 19:52:19
*/
@Mapper(componentModel = "spring")
public interface UsersMapper {

    Users toEntity(UsersDTO dto);

    UsersDTO toDto(Users entity);

}