package com.gae.piaz.autogen.repositorygen;

import com.gae.piaz.autogen.model.Orders;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
* Generated by Springboot-3layer-Generator at 27 ott 2020, 18:23:45
*/
@Repository
public interface OrdersRepository extends JpaRepository<Orders, java.lang.Integer> {

}