package com.example.demo.service.mapper;

import com.example.demo.model.User;
import com.example.demo.controller.dto.UserDTO;
import org.mapstruct.Mapper;

/**
* Generated by Springboot-3layer-Generator at Feb 26, 2023, 4:26:01 PM
*/
@Mapper(componentModel = "spring")
public interface UserMapper {

    User toEntity(UserDTO dto);

    UserDTO toDto(User entity);

}