package com.example.demo.controller;

import org.springframework.data.domain.Page;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;

/**
* Generated by Springboot-3layer-Generator at Feb 21, 2023, 8:01:16 AM
*/
public interface CrudController<O,P>{

    @PostMapping
    ResponseEntity<O> create(O object);

    @PutMapping
    ResponseEntity<O> update(O object);

    @GetMapping("list")
    ResponseEntity<Page<O>> read(Integer page, Integer size);

    @GetMapping("{id}")
    ResponseEntity<O> readOne(P primaryKey);

    @DeleteMapping
    void delete(P primaryKey);

}