package com.gae.piaz.autogen.servicegen;

import com.gae.piaz.autogen.model.Orders;
import com.gae.piaz.autogen.repositorygen.OrdersRepository;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Example;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;

/**
* Generated by Springboot-3layer-Generator at 27 ott 2020, 18:23:45
*/
@Service
public class OrdersService implements CrudService<Orders,java.lang.Integer> {

    @Autowired
    private OrdersRepository repository;

    @Override
    public Orders create(Orders entity) {
        return repository.save(entity);
    }

    @Override
    public Orders update(Orders entity) {
        return repository.save(entity);
    }

    @Override
    public Page<Orders> read(Orders entity, Pageable pageable) {
        Example<Orders> example = Example.of(entity);
        return repository.findAll(example,pageable);
    }

    @Override
    public Orders readOne(java.lang.Integer primaryKey) {
        return repository.getOne(primaryKey);
    }

    @Override
    public void delete(java.lang.Integer primaryKey) {
        repository.deleteById(primaryKey);
    }
}