package com.gae.piaz.autogen.servicegen;

import com.gae.piaz.autogen.model.Personphone;
import com.gae.piaz.autogen.repositorygen.PersonphoneRepository;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Example;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;

/**
* Generated by Springboot-3layer-Generator at 27 ott 2020, 18:23:45
*/
@Service
public class PersonphoneService implements CrudService<Personphone,java.lang.Integer> {

    @Autowired
    private PersonphoneRepository repository;

    @Override
    public Personphone create(Personphone entity) {
        return repository.save(entity);
    }

    @Override
    public Personphone update(Personphone entity) {
        return repository.save(entity);
    }

    @Override
    public Page<Personphone> read(Personphone entity, Pageable pageable) {
        Example<Personphone> example = Example.of(entity);
        return repository.findAll(example,pageable);
    }

    @Override
    public Personphone readOne(java.lang.Integer primaryKey) {
        return repository.getOne(primaryKey);
    }

    @Override
    public void delete(java.lang.Integer primaryKey) {
        repository.deleteById(primaryKey);
    }
}