package com.autogen.example.controller.dto;

import lombok.Data;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

/**
* Generated by Springboot-3layer-Generator at 27 ott 2020, 19:52:19
*/
@Data
public class BooksDTO {

    private java.lang.Integer bookId;
    private java.lang.String title;
    private java.lang.String author;
    private java.lang.String isbn;
    private java.lang.Integer year;

}
