package com.example.demo.service.mapper;

import com.example.demo.model.Books;
import com.example.demo.controller.dto.BooksDTO;
import org.mapstruct.Mapper;

/**
* Generated by Springboot-3layer-Generator at 28 ott 2020, 15:31:03
*/
@Mapper(componentModel = "spring")
public interface BooksMapper {

    Books toEntity(BooksDTO dto);

    BooksDTO toDto(Books entity);

}