package com.example.demo.service.mapper;

import com.example.demo.model.Carts;
import com.example.demo.controller.dto.CartsDTO;
import org.mapstruct.Mapper;

/**
* Generated by Springboot-3layer-Generator at 28 ott 2020, 15:31:03
*/
@Mapper(componentModel = "spring")
public interface CartsMapper {

    Carts toEntity(CartsDTO dto);

    CartsDTO toDto(Carts entity);

}