package com.example.demo.service.mapper;

import com.example.demo.model.Carts;
import com.example.demo.controller.dto.CartsDTO;
import org.mapstruct.Mapper;

/**
* Generated by Springboot-3layer-Generator at 1 nov 2020, 11:10:29
*/
@Mapper(componentModel = "spring")
public interface CartsMapper {

    Carts toEntity(CartsDTO dto);

    CartsDTO toDto(Carts entity);

}