package com.example.demo.service.mapper;

import com.example.demo.model.Carts;
import com.example.demo.controller.dto.CartsDTO;
import org.mapstruct.Mapper;

/**
* Generated by Springboot-3layer-Generator at 31 ott 2020, 17:25:45
*/
@Mapper(componentModel = "spring")
public interface CartsMapper {

    Carts toEntity(CartsDTO dto);

    CartsDTO toDto(Carts entity);

}