package com.example.demo.service.mapper;

import com.example.demo.model.Orders;
import com.example.demo.controller.dto.OrdersDTO;
import org.mapstruct.Mapper;

/**
* Generated by Springboot-3layer-Generator at 31 ott 2020, 17:25:45
*/
@Mapper(componentModel = "spring")
public interface OrdersMapper {

    Orders toEntity(OrdersDTO dto);

    OrdersDTO toDto(Orders entity);

}