package com.example.demo.service.mapper;

import com.example.demo.model.Orders;
import com.example.demo.controller.dto.OrdersDTO;
import org.mapstruct.Mapper;

/**
* Generated by Springboot-3layer-Generator at 28 ott 2020, 15:31:03
*/
@Mapper(componentModel = "spring")
public interface OrdersMapper {

    Orders toEntity(OrdersDTO dto);

    OrdersDTO toDto(Orders entity);

}