package com.example.demo.service.mapper;

import com.example.demo.model.Personphone;
import com.example.demo.controller.dto.PersonphoneDTO;
import org.mapstruct.Mapper;

/**
* Generated by Springboot-3layer-Generator at 28 ott 2020, 15:31:03
*/
@Mapper(componentModel = "spring")
public interface PersonphoneMapper {

    Personphone toEntity(PersonphoneDTO dto);

    PersonphoneDTO toDto(Personphone entity);

}