package com.example.demo.service.mapper;

import com.example.demo.model.Users;
import com.example.demo.controller.dto.UsersDTO;
import org.mapstruct.Mapper;

/**
* Generated by Springboot-3layer-Generator at 28 ott 2020, 15:31:03
*/
@Mapper(componentModel = "spring")
public interface UsersMapper {

    Users toEntity(UsersDTO dto);

    UsersDTO toDto(Users entity);

}