package com.example.demo.serviceInterface.impl;

import com.example.demo.model.Order;
import com.example.demo.repository.OrderRepository;
import com.example.demo.serviceInterface.OrderService;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Example;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import java.util.Optional;

/**
* Generated by Springboot-3layer-Generator at Feb 26, 2023, 4:11:11 PM
*/
@Service
public class OrderServiceBean implements OrderService {

    @Autowired
    private OrderRepository repository;

    @Override
    public Order create(Order entity) {
        return repository.save(entity);
    }

    @Override
    public Order update(Order entity) {
        return repository.save(entity);
    }

    @Override
    public Page<Order> find(Order entity, Pageable pageable) {
        Example<Order> example = Example.of(entity);
        return repository.findAll(example,pageable);
    }

    @Override
    public Optional<Order> getOne(java.lang.Integer primaryKey) {
        return repository.findById(primaryKey);
    }

    @Override
    public void delete(java.lang.Integer primaryKey) {
        repository.deleteById(primaryKey);
    }
}