package com.example.demo.serviceInterface.impl;

import com.example.demo.model.User;
import com.example.demo.repository.UserRepository;
import com.example.demo.serviceInterface.UserService;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Example;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import java.util.Optional;

/**
* Generated by Springboot-3layer-Generator at Feb 26, 2023, 4:08:20 PM
*/
@Service
public class UserServiceBean implements UserService {

    @Autowired
    private UserRepository repository;

    @Override
    public User create(User entity) {
        return repository.save(entity);
    }

    @Override
    public User update(User entity) {
        return repository.save(entity);
    }

    @Override
    public Page<User> find(User entity, Pageable pageable) {
        Example<User> example = Example.of(entity);
        return repository.findAll(example,pageable);
    }

    @Override
    public Optional<User> getOne(java.lang.Integer primaryKey) {
        return repository.findById(primaryKey);
    }

    @Override
    public void delete(java.lang.Integer primaryKey) {
        repository.deleteById(primaryKey);
    }
}