package com.example.demo.serviceInterface.mapper;

import com.example.demo.model.User;
import com.example.demo.controller.dto.UserDTO;
import org.mapstruct.Mapper;

/**
* Generated by Springboot-3layer-Generator at Feb 22, 2023, 1:38:03 PM
*/
@Mapper(componentModel = "spring")
public interface UserMapper {

    User toEntity(UserDTO dto);

    UserDTO toDto(User entity);

}