package com.example.demo.repository;

import com.example.demo.model.Users;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
* Generated by Springboot-3layer-Generator at 28 ott 2020, 15:31:03
*/
@Repository
public interface UsersRepository extends JpaRepository<Users, java.lang.Integer> {

}