package com.example.demo.repository;

import com.example.demo.model.User;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
* Generated by Springboot-3layer-Generator at Feb 26, 2023, 4:08:34 PM
*/
@Repository
public interface UserRepository extends JpaRepository<User, java.lang.Integer> {

}