package com.example.demo.repository;

import com.example.demo.model.User;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
* Generated by Springboot-3layer-Generator at Jan 23, 2023, 10:35:30 AM
*/
@Repository
public interface UserRepository extends JpaRepository<User, java.lang.Integer> {

}